### ISSUE TITLE
sync not starting, says: Error: Repository ol8_u7_baseos_base is listed more than once in the configuration

### ISSUE THREAD

**Issue by win2key** [Djelibeybi/oraclelinux-reposync#11]
[root@amiga oraclelinux-reposync]# podman run --rm -it   --name ol-repo-sync   -v ${PWD}/config:/config:z   -v ${PWD}/repo:/repo:z   ol-repo-sync 
Verifying required volume mounted directories have be configured:
  => required directory /repo found.
  => required directory /config found.

Verifying files required to sync:
  => required file /config/repo-map.json found.
  => required file /config/repos.json found.

Verifying files required for ULN sync:
  => required ULN configuration file /config/uln.conf found.
  => required ULN configuration file /etc/sysconfig/rhn/systemid not found: ULN repo sync disabled.

Verified /config/repos.json contains valid JSON.
Starting sync.
This system is not registered with Unbreakable Linux Network or Spacewalk.
Unbreakable Linux Network or Spacewalk based repositories will be disabled.
Error: Repository ol8_u7_baseos_base is listed more than once in the configuration

[root@amiga oraclelinux-reposync]# cat config/repos.json 
{
    "yum": [
        "ol8_u7_baseos_base",
        "ol8_appstream",
        "ol8_kvm_appstream"
    ]
}

**Comment by Djelibeybi** [comment]
I'll have to see if I can reproduce this later in the week.

**Comment by Djelibeybi** [comment]
I haven't had a chance to create a test environment for this. In the meantime, could you please replace `ol8_u7_baseos_base` with `ol8_baseos_latest` to see if that works? 

The content of the `ol8_u7_baseos_base` repo can be found on the OL8U7 ISO and doesn't need to be synced. It's also very, very out of date and insecure, so you shouldn't be using it for production systems at all.

Keep in mind that both `ol8_appstream` and `ol8_kvm_appstream` assume that `ol8_baseos_latest` is enabled so that the latest package versions are available as dependencies.

**Comment by bschonec** [comment]
I have the same issue.  The problem is because the repository that is being defined in the 'reposync' command is already defined in /etc/yum.repos.d file/files.  Perhaps a script that zeros out any entries in the .repo file would solve the problem?

**Comment by Djelibeybi** [comment]
This error can actually be ignored. The sync doesn't use the repos as configured in `/etc/yum.repos.d` so `dnf` is just being noisy. Though, it seems that the behaviour of the `repoid` parameter has changed: when I created this project, it would disable all other repos and this error was not seen. Now it appears that is no longer happening.

If the sync isn't working, please open a new issue.
